from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = ' https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '7cc2c3d0-1d08-4ad3-91fe-289bbb58631e',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

In [5]:
import pandas as pd 

pd.set_option('display.max_columns', None)
crypto = pd.json_normalize(data['data'])

crypto.head(5)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,10520,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.953429e+07,19534287,False,NaN,1,NaN,NaN,NaN,2023-11-05T20:53:00.000Z,35044.358127,1.172220e+10,31.6648,0.014302,0.762015,1.235549,25.202601,36.457470,20.245804,6.845665e+11,51.8954,7.359315e+11,NaN,2023-11-05T20:53:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,7706,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.202689e+08,120268913.449319,True,NaN,2,NaN,NaN,NaN,2023-11-05T20:53:00.000Z,1888.030966,8.261641e+09,76.8321,-0.232300,2.602390,5.027772,14.586662,15.925903,3.482617,2.270714e+11,17.2130,2.270714e+11,NaN,2023-11-05T20:53:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,65115,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,8.536776e+10,88623656723.666138,True,NaN,3,NaN,NaN,NaN,2023-11-05T20:52:00.000Z,1.000806,2.637396e+10,35.1081,0.004969,0.009829,0.040495,0.033400,0.144410,0.203207,8.543658e+10,6.4765,8.869511e+10,NaN,2023-11-05T20:52:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,1740,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.517029e+08,151702859.540038,False,NaN,4,NaN,NaN,NaN,2023-11-05T20:52:00.000Z,244.077994,3.999517e+08,53.2776,0.138847,3.284135,7.464930,14.272960,13.688345,1.045233,3.702733e+10,2.8070,3.702733e+10,NaN,2023-11-05T20:52:00.000Z,NaN,NaN,NaN,NaN,NaN
4,52,XRP,XRP,xrp,1132,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, arr...",1.000000e+11,5.361584e+10,99988316618,False,NaN,5,NaN,NaN,NaN,2023-11-05T20:53:00.000Z,0.652994,1.808787e+09,117.8713,-0.686438,6.455816,16.662828,23.930635,30.301753,5.979459,3.501082e+10,2.6540,6.529940e+10,NaN,2023-11-05T20:53:00.000Z,NaN,NaN,NaN,NaN,NaN

In [6]:
crypto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  5000 non-null   int64
 1   name                                5000 non-null   object
 2   symbol                              5000 non-null   object
 3   slug                                5000 non-null   object
 4   num_market_pairs                    5000 non-null   int64
 5   date_added                          5000 non-null   object
 6   tags                                5000 non-null   object
 7   max_supply                          3773 non-null   float64
 8   circulating_supply                  5000 non-null   float64
 9   total_supply                        5000 non-null   object
 10  infinite_supply                     5000 non-null   bool
 11  platform                            0 non-null      float64
 12  cmc_rank                            5000 non-null   int64
 13  self_reported_circulating_supply    2733 non-null   float64
 14  self_reported_market_cap            2733 non-null   float64
 15  tvl_ratio                           83 non-null     float64
 16  last_updated                        5000 non-null   object
 17  quote.USD.price                     5000 non-null   float64
 18  quote.USD.volume_24h                5000 non-null   float64
 19  quote.USD.volume_change_24h         5000 non-null   float64
 20  quote.USD.percent_change_1h         5000 non-null   float64
 21  quote.USD.percent_change_24h        5000 non-null   float64
 22  quote.USD.percent_change_7d         5000 non-null   float64
 23  quote.USD.percent_change_30d        5000 non-null   float64
 24  quote.USD.percent_change_60d        5000 non-null   float64
 25  quote.USD.percent_change_90d        5000 non-null   float64
 26  quote.USD.market_cap                5000 non-null   float64
 27  quote.USD.market_cap_dominance      5000 non-null   float64
 28  quote.USD.fully_diluted_market_cap  5000 non-null   float64
 29  quote.USD.tvl                       89 non-null     float64
 30  quote.USD.last_updated              5000 non-null   object
 31  platform.id                         4254 non-null   float64
 32  platform.name                       4254 non-null   object
 33  platform.symbol                     4254 non-null   object
 34  platform.slug                       4254 non-null   object
 35  platform.token_address              4254 non-null   object
dtypes: bool(1), float64(20), int64(3), object(12)
memory usage: 1.3+ MB

In [7]:
#Converting date colimns to date time

crypto['date_added'] = pd.to_datetime(crypto['date_added'])
crypto['last_updated'] = pd.to_datetime(crypto['last_updated'])
crypto['quote.USD.last_updated'] = pd.to_datetime(crypto['quote.USD.last_updated'])

crypto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  5000 non-null   int64
 1   name                                5000 non-null   object
 2   symbol                              5000 non-null   object
 3   slug                                5000 non-null   object
 4   num_market_pairs                    5000 non-null   int64
 5   date_added                          5000 non-null   datetime64[ns, UTC]
 6   tags                                5000 non-null   object
 7   max_supply                          3773 non-null   float64
 8   circulating_supply                  5000 non-null   float64
 9   total_supply                        5000 non-null   object
 10  infinite_supply                     5000 non-null   bool
 11  platform                            0 non-null      float64
 12  cmc_rank                            5000 non-null   int64
 13  self_reported_circulating_supply    2733 non-null   float64
 14  self_reported_market_cap            2733 non-null   float64
 15  tvl_ratio                           83 non-null     float64
 16  last_updated                        5000 non-null   datetime64[ns, UTC]
 17  quote.USD.price                     5000 non-null   float64
 18  quote.USD.volume_24h                5000 non-null   float64
 19  quote.USD.volume_change_24h         5000 non-null   float64
 20  quote.USD.percent_change_1h         5000 non-null   float64
 21  quote.USD.percent_change_24h        5000 non-null   float64
 22  quote.USD.percent_change_7d         5000 non-null   float64
 23  quote.USD.percent_change_30d        5000 non-null   float64
 24  quote.USD.percent_change_60d        5000 non-null   float64
 25  quote.USD.percent_change_90d        5000 non-null   float64
 26  quote.USD.market_cap                5000 non-null   float64
 27  quote.USD.market_cap_dominance      5000 non-null   float64
 28  quote.USD.fully_diluted_market_cap  5000 non-null   float64
 29  quote.USD.tvl                       89 non-null     float64
 30  quote.USD.last_updated              5000 non-null   datetime64[ns, UTC]
 31  platform.id                         4254 non-null   float64
 32  platform.name                       4254 non-null   object
 33  platform.symbol                     4254 non-null   object
 34  platform.slug                       4254 non-null   object
 35  platform.token_address              4254 non-null   object
dtypes: bool(1), datetime64[ns, UTC](3), float64(20), int64(3), object(9)
memory usage: 1.3+ MB

In [8]:
# Adding Columns Weekday, Day, Month, Month Names, and Year

crypto["weekday"] = crypto["quote.USD.last_updated"].dt.day_name()
crypto["day"] = crypto["quote.USD.last_updated"].dt.day
crypto["month"] = crypto["quote.USD.last_updated"].dt.month
crypto["month_name"] = crypto["quote.USD.last_updated"].dt.month_name()
crypto["year"] = crypto["quote.USD.last_updated"].dt.year

crypto.head(5)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,weekday,day,month,month_name,year
0,1,Bitcoin,BTC,bitcoin,10520,2010-07-13 00:00:00+00:00,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.953429e+07,19534287,False,NaN,1,NaN,NaN,NaN,2023-11-05 20:53:00+00:00,35044.358127,1.172220e+10,31.6648,0.014302,0.762015,1.235549,25.202601,36.457470,20.245804,6.845665e+11,51.8954,7.359315e+11,NaN,2023-11-05 20:53:00+00:00,NaN,NaN,NaN,NaN,NaN,Sunday,5,11,November,2023
1,1027,Ethereum,ETH,ethereum,7706,2015-08-07 00:00:00+00:00,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.202689e+08,120268913.449319,True,NaN,2,NaN,NaN,NaN,2023-11-05 20:53:00+00:00,1888.030966,8.261641e+09,76.8321,-0.232300,2.602390,5.027772,14.586662,15.925903,3.482617,2.270714e+11,17.2130,2.270714e+11,NaN,2023-11-05 20:53:00+00:00,NaN,NaN,NaN,NaN,NaN,Sunday,5,11,November,2023
2,825,Tether USDt,USDT,tether,65115,2015-02-25 00:00:00+00:00,"[payments, stablecoin, asset-backed-stablecoin...",NaN,8.536776e+10,88623656723.666138,True,NaN,3,NaN,NaN,NaN,2023-11-05 20:52:00+00:00,1.000806,2.637396e+10,35.1081,0.004969,0.009829,0.040495,0.033400,0.144410,0.203207,8.543658e+10,6.4765,8.869511e+10,NaN,2023-11-05 20:52:00+00:00,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,Sunday,5,11,November,2023
3,1839,BNB,BNB,bnb,1740,2017-07-25 00:00:00+00:00,"[marketplace, centralized-exchange, payments, ...",NaN,1.517029e+08,151702859.540038,False,NaN,4,NaN,NaN,NaN,2023-11-05 20:52:00+00:00,244.077994,3.999517e+08,53.2776,0.138847,3.284135,7.464930,14.272960,13.688345,1.045233,3.702733e+10,2.8070,3.702733e+10,NaN,2023-11-05 20:52:00+00:00,NaN,NaN,NaN,NaN,NaN,Sunday,5,11,November,2023
4,52,XRP,XRP,xrp,1132,2013-08-04 00:00:00+00:00,"[medium-of-exchange, enterprise-solutions, arr...",1.000000e+11,5.361584e+10,99988316618,False,NaN,5,NaN,NaN,NaN,2023-11-05 20:53:00+00:00,0.652994,1.808787e+09,117.8713,-0.686438,6.455816,16.662828,23.930635,30.301753,5.979459,3.501082e+10,2.6540,6.529940e+10,NaN,2023-11-05 20:53:00+00:00,NaN,NaN,NaN,NaN,NaN,Sunday,5,11,November,2023

In [ ]:
#Dropping unnecessary columns 

crypto.drop(['platform','self_reported_circulating_supply',
             'self_reported_market_cap','tvl_ratio',
            'platform.id','platform.name','platform.symbol',
            'platform.slug','platform.token_address'],axis=1)

In [24]:
crypto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  5000 non-null   int64
 1   name                                5000 non-null   object
 2   symbol                              5000 non-null   object
 3   slug                                5000 non-null   object
 4   num_market_pairs                    5000 non-null   int64
 5   date_added                          5000 non-null   datetime64[ns, UTC]
 6   tags                                5000 non-null   object
 7   max_supply                          3773 non-null   float64
 8   circulating_supply                  5000 non-null   float64
 9   total_supply                        5000 non-null   object
 10  infinite_supply                     5000 non-null   bool
 11  cmc_rank                            5000 non-null   int64
 12  last_updated                        5000 non-null   datetime64[ns, UTC]
 13  quote.USD.price                     5000 non-null   float64
 14  quote.USD.volume_24h                5000 non-null   float64
 15  quote.USD.volume_change_24h         5000 non-null   float64
 16  quote.USD.percent_change_1h         5000 non-null   float64
 17  quote.USD.percent_change_24h        5000 non-null   float64
 18  quote.USD.percent_change_7d         5000 non-null   float64
 19  quote.USD.percent_change_30d        5000 non-null   float64
 20  quote.USD.percent_change_60d        5000 non-null   float64
 21  quote.USD.percent_change_90d        5000 non-null   float64
 22  quote.USD.market_cap                5000 non-null   float64
 23  quote.USD.market_cap_dominance      5000 non-null   float64
 24  quote.USD.fully_diluted_market_cap  5000 non-null   float64
 25  quote.USD.tvl                       89 non-null     float64
 26  quote.USD.last_updated              5000 non-null   datetime64[ns, UTC]
 27  weekday                             5000 non-null   object
 28  day                                 5000 non-null   int64
 29  month                               5000 non-null   int64
 30  month_name                          5000 non-null   object
 31  year                                5000 non-null   int64
dtypes: bool(1), datetime64[ns, UTC](3), float64(15), int64(6), object(7)
memory usage: 1.2+ MB

In [27]:
print("Shape of dataset  ",crypto.shape)
print("# of rows in dataset  ",crypto.shape[0])
print("# of columns in dataset  ",crypto.shape[1])

Shape of dataset   (5000, 32)
# of rows in dataset   5000
# of columns in dataset   32

In [32]:
# Push to CSV

crypto.to_csv('Crypto_API_Data.csv')

In [ ]:
#Import gbq
from pandas.io import gbq

In [60]:
# Import CSV Data
cmc = pd.read_csv('/Users/dazhonhunt/Crypto_API_Data.csv')

cmc.head(5)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,cmc_rank,last_updated,quote_USD_price,quote_USD_volume_24h,quote_USD_volume_change_24h,quote_USD_percent_change_1h,quote_USD_percent_change_24h,quote_USD_percent_change_7d,quote_USD_percent_change_30d,quote_USD_percent_change_60d,quote_USD_percent_change_90d,quote_USD_market_cap,quote_USD_market_cap_dominance,quote_USD_fully_diluted_market_cap,quote_USD_tvl,quote_USD_last_updated,weekday,day,month,month_name,year
0,1,Bitcoin,BTC,bitcoin,10520,2010-07-13 00:00:00+00:00,"['mineable', 'pow', 'sha-256', 'store-of-value...",2.100000e+07,1.953429e+07,1.953429e+07,False,1,2023-11-05 20:53:00+00:00,35044.358130,1.172220e+10,31.6648,0.014302,0.762015,1.235549,25.202601,36.457470,20.245804,6.845670e+11,51.8954,7.359320e+11,NaN,2023-11-05 20:53:00+00:00,Sunday,5,11,November,2023
1,1027,Ethereum,ETH,ethereum,7706,2015-08-07 00:00:00+00:00,"['pos', 'smart-contracts', 'ethereum-ecosystem...",NaN,1.202689e+08,1.202689e+08,True,2,2023-11-05 20:53:00+00:00,1888.030966,8.261641e+09,76.8321,-0.232300,2.602390,5.027772,14.586662,15.925903,3.482617,2.270710e+11,17.2130,2.270710e+11,NaN,2023-11-05 20:53:00+00:00,Sunday,5,11,November,2023
2,825,Tether USDt,USDT,tether,65115,2015-02-25 00:00:00+00:00,"['payments', 'stablecoin', 'asset-backed-stabl...",NaN,8.536776e+10,8.862366e+10,True,3,2023-11-05 20:52:00+00:00,1.000806,2.637396e+10,35.1081,0.004969,0.009829,0.040495,0.033400,0.144410,0.203207,8.543658e+10,6.4765,8.869511e+10,NaN,2023-11-05 20:52:00+00:00,Sunday,5,11,November,2023
3,1839,BNB,BNB,bnb,1740,2017-07-25 00:00:00+00:00,"['marketplace', 'centralized-exchange', 'payme...",NaN,1.517029e+08,1.517029e+08,False,4,2023-11-05 20:52:00+00:00,244.077993,3.999517e+08,53.2776,0.138847,3.284135,7.464930,14.272960,13.688345,1.045233,3.702733e+10,2.8070,3.702733e+10,NaN,2023-11-05 20:52:00+00:00,Sunday,5,11,November,2023
4,52,XRP,XRP,xrp,1132,2013-08-04 00:00:00+00:00,"['medium-of-exchange', 'enterprise-solutions',...",1.000000e+11,5.361584e+10,9.998832e+10,False,5,2023-11-05 20:53:00+00:00,0.652994,1.808787e+09,117.8713,-0.686438,6.455816,16.662828,23.930635,30.301753,5.979459,3.501082e+10,2.6540,6.529940e+10,NaN,2023-11-05 20:53:00+00:00,Sunday,5,11,November,2023

In [61]:
# Connect to Google CLoud API to Upload Crypto Dataframe
cmc.to_gbq(destination_table='cmc_API_11623.cmc_data',
           project_id='crypto-df-load',
          if_exists='fail')

100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 1408.90it/s]